### PR TITLE
add search works addin

### PR DESCRIPTION
**Pull request by haozhu233**
Per issue #148, I added a panel in the addin that allows users to search articles through cr_works. Please review.

## Related Issue
#148

## Example
screen shot 2018-02-22 at 10 38 37 am

### CODE REVIEW

**Comment by haozhu233** [comment]
Note that right now I only provide the top 100 results. @sckott do you think it's enough?

**Comment by sckott** [comment]
> I guess People can always use the advanced search on the mainsite to find the correct DOI.

what do you mean by the main site?

**Comment by haozhu233** [comment]
ha, I mean the the crossref site. As I said, for this addin, I only downloaded the first 100 results. I personally feel like that's enough for such an "addin". If people needs to go beyond 100 here, they probably should consider go to crossref.org and use the filtering tools over there.

**Comment by sckott** [comment]
okay, thanks. makes sense. i agree that 100 is enough

i'll have a look at it now

**Comment by haozhu233** [comment]
I made another tiny change.

**Comment by sckott** [comment]
LGTM

**Pull request merged**
