### PR TITLE
Major update to the crossref addin

### PR DESCRIPTION
**Pull request by haozhu233**
I made quite some updates to the addin and now it's a lot more useful than the initial version. The goal is to build something similar with google scholar and mendeley, but within RStudio. I would love to hear some feedback.

screen shot 2018-09-06 at 2 22 19 pm

### CODE REVIEW

**Comment by sckott** [comment]
thanks for this @haozhu233  - on vacation now, will respond mid next week

**Comment by sckott** [comment]
having a look now

**Comment by haozhu233** [comment]
I’ll look into that. 😆

**Comment by haozhu233** [comment]
@sckott Finally got a time to sit down and fix this little bug. XD

**Comment by sckott** [comment]
LGTM @haozhu233

**Pull request merged**
