### PR TITLE
Provide contact information to Crossref

### PR DESCRIPTION
**Pull request by njahn82**
Crossref has recently begun to encourage API calls that have contact information. API users who send email together with the API request will be directed to a special pool of API machines.

https://github.com/CrossRef/rest-api-doc#etiquette

In this pull request, I added email as an optional parameter, and included an email validation function. Hope, I caught all relevant calls.

### CODE REVIEW

**Comment by sckott** [comment]
Thanks @njahn82 !!! Was just implementing this in the python and ruby clients. 

I'd prefer to pass the mailto in the header instead of as a query param. is that okay?  If so, can you change it to add to the user agent string constructor (https://github.com/ropensci/rcrossref/blob/master/R/zzz.R#L15)? Could add it as a param to `rcrossref_ua()`, with default `NULL`, so no mailto added if it's absent, so user agent string would then look like e.g., `r-curl/3.0 crul/0.4.0 rOpenSci(rcrossref/0.7.0) (mailto:foo@bar.com)`

or is there a strong argument for passing as a query param?

**Comment by njahn82** [comment]
Sounds good, will pass email to `rcrossref_ua()`. It will also mean less code. Will add it by tomorrow.

**Comment by njahn82** [comment]
Hi @sckott , email can now be shared via the user agent string when it is stored in `.Renviron` following this `httr` vignette <https://cran.r-project.org/web/packages/httr/vignettes/secrets.html>. Such implementation only requires small changes in the source code. 

Please let me know what you think of this approach.

**Comment by njahn82** [comment]
Sorry, I got some GIT merging issues, will try again

**Comment by sckott** [comment]
ok

**Pull request closed without merging**
