### PR TITLE
Added an "Add Crossref Citations" Rstudio addin

### PR DESCRIPTION
**Pull request by haozhu233**
Hi, Scott,

Following what I said in my email, I just made a draft of a Rstudio addin, that will save crossref citations to a local bib file. Please review it when you have time. :)

Screenshots:
screenshot 2016-07-22 10 22 58
screenshot 2016-07-22 10 23 08

### CODE REVIEW

**Comment by sckott** [comment]
Thanks, will have a look

**Comment by sckott** [comment]
@haozhu233 had a look:

* can you possibly give the labels for each citation something related to the paper? e.g., I put in two DOIs 10.1002/(issn)1939-9170 and 10.4996/fireecology and the gave 

```
@misc{1,
	doi = {10.1002/(issn)1939-9170},
	url = {http://dx.doi.org/10.1002/(issn)1939-9170},
	publisher = {Wiley-Blackwell},
	title = {Ecology}
}

@misc{1,
	doi = {10.4996/fireecology},
	url = {http://dx.doi.org/10.4996/fireecology},
	publisher = {Association for Fire Ecology},
	title = {Fire Ecology}
}
```

both labeled with `1` - I realize those two citations do not have author information, but perhaps they can be labeled uniquely somehow

* I noticed when using the add when you do a 2nd or 3rd press of _Add My Citations_  with a DOI you don't get the info printed as you do on the first, e.g., see below

screen shot 2016-07-22 at 4 09 15 pm

**Comment by haozhu233** [comment]
@sckott Hi, Scott, I just made some changes to this PR to fulfill your feature request and fix that bug.

Now you will have the first word of the title as label if author is not available
```
@misc{Ecology,
	doi = {10.1002/(issn)1939-9170},
	url = {http://dx.doi.org/10.1002/(issn)1939-9170},
	publisher = {Wiley-Blackwell},
	title = {Ecology}
}

@misc{Fire,
	doi = {10.4996/fireecology},
	url = {http://dx.doi.org/10.4996/fireecology},
	publisher = {Association for Fire Ecology},
	title = {Fire Ecology}
}
```

I also fixed that bug that will disable the preview of 2nd (or later) entry. Please review. Thanks! :)

**Comment by sckott** [comment]
thanks, looks better, though on check I get

```r
✔  checking foreign function calls
N  checking R code for possible problems
   crAddins : server: no visible global function definition for
     ‘reactiveValues’
   Undefined global functions or variables:
     reactiveValues
```

**Comment by haozhu233** [comment]
Sorry, I forgot to add that to the NAMESPACE. Now it's in. :)

**Comment by sckott** [comment]
thanks!

**Pull request merged**
