### PR TITLE
handle DOI / ISSN that don't exist #53

### PR DESCRIPTION
**Pull request by njahn82**
Assuming that every work registered with CrossRef has a doi and every journal a issn, I'd just exclude rows with missing doi resp. issn from the resulting data frame.

### CODE REVIEW

**Comment by sckott** [comment]
@njahn82 can you adda test or two for these changes?

**Comment by sckott** [comment]
also, thanks for the PR

**Comment by njahn82** [comment]
@sckott thanks for all the ropenci packages

**Comment by sckott** [comment]
@njahn82 thanks, looks good

**Pull request merged**
